package com.product.aji.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ITEM".
 */
@Entity
public class Item {

    @Id(autoincrement = true)
    private Long id;
    private String judul;
    private String pemasok;
    private String jumlah;
    private String tanggal;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Item() {
    }

    public Item(Long id) {
        this.id = id;
    }

    @Generated
    public Item(Long id, String judul, String pemasok, String jumlah, String tanggal) {
        this.id = id;
        this.judul = judul;
        this.pemasok = pemasok;
        this.jumlah = jumlah;
        this.tanggal = tanggal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJudul() {
        return judul;
    }

    public void setJudul(String judul) {
        this.judul = judul;
    }

    public String getPemasok() {
        return pemasok;
    }

    public void setPemasok(String pemasok) {
        this.pemasok = pemasok;
    }

    public String getJumlah() {
        return jumlah;
    }

    public void setJumlah(String jumlah) {
        this.jumlah = jumlah;
    }

    public String getTanggal() {
        return tanggal;
    }

    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
