package com.product.aji.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ITEM".
*/
public class ItemDao extends AbstractDao<Item, Long> {

    public static final String TABLENAME = "ITEM";

    /**
     * Properties of entity Item.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Judul = new Property(1, String.class, "judul", false, "JUDUL");
        public final static Property Pemasok = new Property(2, String.class, "pemasok", false, "PEMASOK");
        public final static Property Jumlah = new Property(3, String.class, "jumlah", false, "JUMLAH");
        public final static Property Tanggal = new Property(4, String.class, "tanggal", false, "TANGGAL");
    }


    public ItemDao(DaoConfig config) {
        super(config);
    }
    
    public ItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JUDUL\" TEXT," + // 1: judul
                "\"PEMASOK\" TEXT," + // 2: pemasok
                "\"JUMLAH\" TEXT," + // 3: jumlah
                "\"TANGGAL\" TEXT);"); // 4: tanggal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Item entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String judul = entity.getJudul();
        if (judul != null) {
            stmt.bindString(2, judul);
        }
 
        String pemasok = entity.getPemasok();
        if (pemasok != null) {
            stmt.bindString(3, pemasok);
        }
 
        String jumlah = entity.getJumlah();
        if (jumlah != null) {
            stmt.bindString(4, jumlah);
        }
 
        String tanggal = entity.getTanggal();
        if (tanggal != null) {
            stmt.bindString(5, tanggal);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Item entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String judul = entity.getJudul();
        if (judul != null) {
            stmt.bindString(2, judul);
        }
 
        String pemasok = entity.getPemasok();
        if (pemasok != null) {
            stmt.bindString(3, pemasok);
        }
 
        String jumlah = entity.getJumlah();
        if (jumlah != null) {
            stmt.bindString(4, jumlah);
        }
 
        String tanggal = entity.getTanggal();
        if (tanggal != null) {
            stmt.bindString(5, tanggal);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Item readEntity(Cursor cursor, int offset) {
        Item entity = new Item( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // judul
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pemasok
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // jumlah
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // tanggal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Item entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJudul(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPemasok(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setJumlah(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTanggal(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Item entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Item entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Item entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
